@startuml
title Чтение метаданных фото

start
:Чтение пути фото;

if (Есть ли в БД?) then (Да)
  :Чтение "размер + mtime\n+ быстрый хэш";
  if (Совпадает ли хэш?) then (Да)
    :Читаем метаданные из БД;
    stop
  else (Нет)
    if (В БД данные свежее?) then (Да)
      :Читаем метаданные из БД;
      stop
    else (Нет)
      :Спросить пользователя,\nкакие данные принимаем;
      if (Какие данные?) then (Из базы данных)
        :Обновляем хеш в БД;
        :Читаем метаданные из БД;
        stop
      else (Из фото)
        :Добавление метаданных в БД;
        stop
      endif
    endif
  endif
else (Нет)
  :Чтение метаданных фото;
  :Добавление метаданных в БД;
  stop
endif
@enduml